export const toolkitConstants = {
    TODAY_ACTIVITY: 'TODAY_ACTIVITY',
    SET_WEEKLY_POSTS: 'WEEKLY_TOOLKIT_POSTS',
    SET_TOOLKIT_RECIPES: 'TOOLKIT_RECIPES',
    TOOLKIT_TYPES: 'TOOLKIT_TYPES',
    GET_ALL_TOOLKIT_POSTS_WITH_TYPE1: 'GET_ALL_TOOLKIT_POSTS_WITH_TYPE1',
    GET_ALL_TOOLKIT_POSTS_WITH_TYPE2: 'GET_ALL_TOOLKIT_POSTS_WITH_TYPE2',
    GET_ALL_TOOLKIT_POSTS_WITH_TYPE3: 'GET_ALL_TOOLKIT_POSTS_WITH_TYPE3',
    GET_ALL_TOOLKIT_POSTS_WITH_TYPE4: 'GET_ALL_TOOLKIT_POSTS_WITH_TYPE4',
    GET_ALL_TOOLKIT_POSTS_WITH_TYPE5: 'GET_ALL_TOOLKIT_POSTS_WITH_TYPE5',
    GET_ALL_TOOLKIT_POSTS_WITH_TYPE6: 'GET_ALL_TOOLKIT_POSTS_WITH_TYPE6',
    GET_ALL_TOOLKIT_POSTS_WITH_TYPE7: 'GET_ALL_TOOLKIT_POSTS_WITH_TYPE7'
}