export const userConstants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT : "LOGOUT",    
    SOCIAL_LOGIN_SUCCESS: "SOCIAL_LOGIN_SUCCESS",
    SET_USER : 'SET_USER',
    UPDATE_USER: 'UPDATE_USER',
    GET_ALL_USERS: 'GET_ALL_USERS'
  };
  